### PR TITLE
Initial utilities.

### PR DESCRIPTION
**Pull request by austinkelleher**
I think this will work pretty well. I've started integrating this into my own hooks project.

Using the `logger`:

```js
    const config = require('~/src/config')
    const projectPackage = require('~/package.json')

    require('windbreaker-service-util/logging')
      .configure({
        packagePath: require.resolve('~/package.json'),
        logLevel: config.getLogLevel(),
        loggerName: projectPackage.name
      })
```

Loading config:

```js
const Config = require('~/models/Config')
const registerConfig = require('windbreaker-service-util/config')

let config = module.exports = new Config()

registerConfig(config, [
  // { ....Something from a file.... }, 
  // { .....process.argv...... },
 // { ... Whatever you want ... }
])

config.load()
```

You can remove `fashion-model` and `fashion-model-defaults` from your projects because they're installed in the shared repo where I expose `models/Model` etc.

Additionally, I have a created a `models/BaseServiceConfig`, which will include the shared configuration options through each service. For example `logLevel`. 

Your config model:

```js
const BaseServiceConfig = require('windbreaker-service-util/models/BaseServiceConfig')

// My custom service config model:
module.exports = BaseServiceConfig.extend({
  properties: {
    httpServerPort: {
      description: 'Port to run the hooks HTTP server port on',
      type: Number
    }
  }
})
```

I will move out the producer/consumer/connection logic into the shared repo once it's more stable.

### CODE REVIEW

**Comment by charlieduong94** [comment]
[Create a windbreaker-server-util repo to share server code](https://trello.com/c/zEpaQo14/29-create-a-windbreaker-server-util-repo-to-share-server-code)

**Comment by Druotic** [comment]
https://trello.com/c/zEpaQo14/29-create-a-windbreaker-server-util-repo-to-share-server-code Charlie and I have been adding card numbers to commits, e.g. "#29 <msg>" for easy tracking later.

**Comment by charlieduong94** [comment]
We should something like https://github.com/austin-rausch/branch-name-commit-modifier to start doing that for us.

**Comment by austinkelleher** [comment]
@charlieduong94 @Druotic I agree we should do that.

**Comment by charlieduong94** [comment]
I'll start converting core over to this once this PR is merged.

**Comment by charlieduong94** [comment]
[Create windbreaker-server-util repo](https://trello.com/c/sInb9UwN/28-create-windbreaker-server-util-repo)

**Pull request merged**
